DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  oauth_provider TEXT DEFAULT NULL,
  oauth_uid TEXT DEFAULT NULL,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT DEFAULT NULL,
  gender TEXT DEFAULT NULL,
  locale TEXT DEFAULT NULL,
  picture TEXT DEFAULT NULL,
  role TEXT DEFAULT 'user',
  created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
